spring:
  cloud:
    gateway:
      routes:
        - id: FRONT_RESOURCE_SERVICE
          uri: http://front
          predicates:
            - Path=/home
        - id: DIARY_SERVICE
          uri: http://backend
          predicates:
            - Path=/diary/**
        - id: AUTHENTICATION_SERVICE
          uri: http://authentication
          predicates:
            - Path=/authentication/**

    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true