spring:
  cloud:
    gateway:
      routes:
        - id: FRONT_RESOURCE_SERVICE
          uri: http://localhost:8888
          predicates:
            - Path=/home
        - id: DIARY_SERVICE
          uri: http://localhost:8080
          predicates:
            - Path=/diary/**
        - id: AUTHENTICATION_SERVICE
          uri: http://localhost:8084
          predicates:
            - Path=/authentication/**

    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true