spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 10000
        max-attempts: 5
        multiplier: 1.5
      request-connect-timeout: 2000
      request-read-timeout: 10000
  config:
    import: "configserver:http://localhost:8087"

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix: WARN
    org.springframework.web: WARN
    com.optimagrowth: DEBUG
