server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful


spring:
  application:
    name: gateway
  lifecycle:
    timeout-per-shutdown-phase: 15s
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: bdGBM40jPg3BsDRk81PKeBzk0RqY4YoE
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/Comma
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:
        - id: psy-service
          uri: ${PSY_SERVICE_URL:http://localhost:9002}
          predicates:
            - Path=/api/psy/**
          filters:
            - RewritePath=^/api/psy/(?<path>.*), /api/v1/$\{path}
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
        - id: diary-service
          uri: ${DIARY_SERVICE_URL:http://localhost:9002}
          predicates:
            - Path=/api/diary/**
          filters:
            - RewritePath=^/api/diary/(?<path>.*), /api/v1/$\{path}
            - name: CircuitBreaker
              args:
                name: CircuitBreaker

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s

management:
  endpoints:
    web:
      exposure:
        include: configprops, env, gateway, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState
logging:
  level:
    org.springframework.security: debug

