spring:
  config:
    activate:
      on-profile: "route"


  cloud:
    gateway:
      routes:
        - id: frontend_route
          uri: http://frontend:80/
          predicates:
            - Path=/frontend/**
        - id: backend_route
          uri: http://backend:8080
          predicates:
            - Path=/backend/**
        - id: authentication_route
          uri: http://authentication:8082
          predicates:
            - Path=/auth/**

      loadbalancer:
        use404: true